//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace TestExample1

module First =
    let fourtyTwo = 42

module Second =
    let fourtyTwo = 42

module Third =
    let fourtyTwo = 42

module Fourth =
    let fourtyTwo = 42

