//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
module First =
    let inline fourtyTwo = 42

module Second =
    let inline fourtyTwo = 42

module Third =
    let inline fourtyTwo = 42

module Fourth =
    let inline fourtyTwo = 42

