//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
namespace rec Test3


namespace rec Test3


namespace rec Test3


namespace rec Test3

module TestDU =
    open Example3

    type TestDUKind =
        | DUcase0
        | DUcase1
        | DUcase2
        | DUcase3

    type TestDU with
        member this.kind =
            match this with
            | TestDU.DUcase0 _ -> TestDUKind.DUcase0
            | TestDU.DUcase1 _ -> TestDUKind.DUcase1
            | TestDU.DUcase2 _ -> TestDUKind.DUcase2
            | TestDU.DUcase3 -> TestDUKind.DUcase3
namespace Test3

module example1 =
    let fourtyTwo = 42
