<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SchemaAsm.fs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchemaTP.Runtime\SchemaTP.Runtime.fsproj" />
  </ItemGroup>

</Project>
