<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Bridge.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.Compiler.Service" Version="43.9.101" />
  </ItemGroup>
</Project>
