namespace Myriad.Core

open System.IO

module Generation =
    /// Set to "true" in a generator's GeneratorContext.AdditionalParameters when its output is appended
    /// to the input file (MyriadInlineGeneration / --inlinegeneration) rather than written to a file of
    /// its own, since the output must then fit into the input file, e.g. without a namespace declaration
    /// after a top-level module. Being a literal, it can be used by plugins running on older Myriad
    /// versions too, where the parameter is simply absent.
    [<Literal>]
    let InlineGenerationParameter = "MyriadInlineGeneration"

    /// Whether the file already consists of exactly the lines File.WriteAllLines would write for `lines`,
    /// whose elements may themselves span several lines. Compares lines rather than bytes, so differences
    /// in line endings or a byte order mark do not count as changes.
    let fileHasLines (path: string) (lines: string seq) =
        let expected =
            lines
            |> Seq.collect (fun line -> line.Split([| "\r\n"; "\n"; "\r" |], System.StringSplitOptions.None))
            |> Seq.toArray

        File.Exists path && File.ReadAllLines path = expected

    let header =
       [   "//------------------------------------------------------------------------------"
           "//        This code was generated by myriad."
           "//        Changes to this file will be lost when the code is regenerated."
           "//------------------------------------------------------------------------------"]

    let getHeaderedCode (formattedCode: string) =
        [ yield! header
          formattedCode ]

    let tryGetHeaderStartingLine (inputFile: string) =
        seq { yield! System.IO.File.ReadLines inputFile }
        |> Seq.tryFindIndex (fun line -> line = header.[1])
        |> Option.map (fun index -> index - 1)

    /// Returns the lines of code minus the code generation header that might be present
    let linesToKeep (inputFile: string) =
        let headerStartingLine = tryGetHeaderStartingLine inputFile
        let inputCode = File.ReadLines(inputFile)
        match headerStartingLine with
        | Some headerStartingLine when headerStartingLine > 0 -> 
            inputCode
            |> Seq.take headerStartingLine
        | _ -> inputCode