<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="MyriadPreview.Runtime">
      <HintPath>..\MyriadPreview.Runtime\bin\Debug\net9.0\MyriadPreview.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
